apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: pedroribeiro
  name: project2-pvc-pedroribeiro
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
  volumeName: project2-pv-pedroribeiro
